#! /bin/sh
# /etc/init.d/ctag-beast
#

case "$1" in
  start)
    echo "Loading CTAG 24CH Beast Overlay..."
    echo BB-CTAG-SW-16CH > /sys/devices/platform/bone_capemgr/slots
    ;;
  *)
    echo "Usage: /etc/init.d/ctag-beast {start}"
    exit 1
    ;;
esac

exit 0
